# Generated by Django 3.1.6 on 2021-02-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperLogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='quotes',
            new_name='Quote',
        ),
    ]
