# Generated by Django 3.1.6 on 2021-02-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperLogin', '0002_auto_20210215_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='author',
            name='dod',
        ),
        migrations.RemoveField(
            model_name='author',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='author',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='author',
            name='shortderc',
        ),
    ]
