# Generated by Django 3.1.6 on 2021-02-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperLogin', '0005_auto_20210217_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialmessages',
            name='quotes_type',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='specialmessages',
            name='quotes',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
